In [51]:
import numpy as np


In [52]:
lst = [1,2,3]
lst1 = [[1,2,3,4],[5,6,7,8]]
type(lst)

list

In [53]:
arr = np.array(lst)        #converting list into array
arr1 = np.array(lst1)
type(arr)
type(arr1)

numpy.ndarray

In [54]:
# arr.ndim                       #checking dimension of array
arr1.ndim


2

In [55]:
arr.size

3

In [56]:
arr.dtype

dtype('int32')

In [57]:
zeros = np.zeros((4,5))                 #making array of 4 rows 5 columns
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
#Generating random number, All the number generated are less than 1 
np.random.random()

0.5274318949243785

In [60]:
#of a specific shape
np.random.random((2,3))

array([[0.44122531, 0.62384397, 0.42129015],
       [0.33941781, 0.60558094, 0.96679576]])

In [61]:
c = np.arange(1,11,1)     #(starting, ending-1, skipping range) 
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
#linspace give numbers that are equidistant from each other 
np.linspace(1,10,19)              #(starting, ending, total numbers that you need)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [63]:
arr = np.random.random((4,3))
arr

array([[0.77676041, 0.71308826, 0.61761974],
       [0.6453353 , 0.23196759, 0.24560579],
       [0.52904495, 0.58243809, 0.93523571],
       [0.74183916, 0.38360923, 0.40819027]])

In [64]:
#now if we want to reshape this arr (means - if we want to keep these values as it is and add one more row or column in this)
arr = np.reshape(arr,(2,6))             #for reshaping it is must to keep the size of array same in both of the cases if in the first array there are 12 elements then in the second as well there should be 12 only
arr

array([[0.77676041, 0.71308826, 0.61761974, 0.6453353 , 0.23196759,
        0.24560579],
       [0.52904495, 0.58243809, 0.93523571, 0.74183916, 0.38360923,
        0.40819027]])

In [65]:
#to convert any array with whatever dimension into 1 row
arr.flatten()


array([0.77676041, 0.71308826, 0.61761974, 0.6453353 , 0.23196759,
       0.24560579, 0.52904495, 0.58243809, 0.93523571, 0.74183916,
       0.38360923, 0.40819027])

In [66]:
arr = np.array([1,2,3,4,5,6])
arr


array([1, 2, 3, 4, 5, 6])

In [67]:
#if we want to do airthmetic operation in any of the array element
print(arr+1)
print(arr-1)
print(arr/7)
print(arr*2)
print(arr**3)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[0.14285714 0.28571429 0.42857143 0.57142857 0.71428571 0.85714286]
[ 2  4  6  8 10 12]
[  1   8  27  64 125 216]


In [68]:
#if want to make changes these in the elements and want to change the array
arr = arr+1
print(arr)
arr *= 2
print(arr)


[2 3 4 5 6 7]
[ 4  6  8 10 12 14]


In [69]:
#if we want to print the minimum or maximum element of the array
print(arr.max())
print(arr.min())

14
4


In [70]:
#For a multidimensional array
arr = np.array([[23,34,23],
                [2,5,6],
                [346,342,453]])
print(arr.min())
print(arr.max())

#if we want to find maximum/minimum element from all the rows/colums
print(arr.max(axis = 1))     #row-wise
print(arr.min(axis=1))

print(arr.min(axis=0))       #column-wise 
print(arr.max(axis=0))

2
453
[ 34   6 453]
[ 23   2 342]
[2 5 6]
[346 342 453]


In [71]:
#sum of the array
arr.sum()

1234

In [72]:
arr1 = np.array([[1,2,3],
                [7,5,4],
                [4,6,7]])

arr2=np.array([[3,3,4],
      [8,6,4],
      [2,4,5]])

arr3=np.array([[3,3,4,7],
      [8,6,4,9],
      [2,4,5,1]])


In [73]:
arr1

array([[1, 2, 3],
       [7, 5, 4],
       [4, 6, 7]])

In [74]:
arr2

array([[3, 3, 4],
       [8, 6, 4],
       [2, 4, 5]])

In [75]:
arr3

array([[3, 3, 4, 7],
       [8, 6, 4, 9],
       [2, 4, 5, 1]])

In [76]:
#if we want to add two arrays of same shape/dimension 
#(will give error in arr1+arr3)
arr1+arr2

array([[ 4,  5,  7],
       [15, 11,  8],
       [ 6, 10, 12]])

In [77]:
#can do different aithmetic operations
arr2*arr1

array([[ 3,  6, 12],
       [56, 30, 16],
       [ 8, 24, 35]])

In [78]:
#can do dot-product as well
arr1.dot(arr2)

array([[25, 27, 27],
       [69, 67, 68],
       [74, 76, 75]])

In [79]:
arr2.dot(arr1)

array([[40, 45, 49],
       [66, 70, 76],
       [50, 54, 57]])

In [80]:
#slicing in array
arr = np.array([1,2,3,4,5])
arr[:-1]            #same as list

array([1, 2, 3, 4])

In [81]:
#slicing in multidimensional array
print(arr1)
print("\n")
print(arr1[:-1,:])                 #[for rows,for columns]
print("\n")
print(arr1[:-1,2:])
print("\n")
print(arr1[1:2,2:])

[[1 2 3]
 [7 5 4]
 [4 6 7]]


[[1 2 3]
 [7 5 4]]


[[3]
 [4]]


[[4]]


Sorting

In [82]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
np.sort(arr,axis=1,kind = 'mergesort')              #(name of array,axis=1 means row 0 means columns, kind asks us about mehtod for sorting) 
#if we don't provide axis and kind it will automatically sort according rows
np.sort(arr)   

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [83]:
np.sort(arr,axis = 0)     #sort according columns

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

Array Merging

In [84]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[8,7,6,5],[4,3,2,1]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [86]:
#for concatinating two arrays
np.vstack((arr1,arr2))              #vstack for vertical merging    

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [87]:
np.vstack((arr2,arr1))      

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.hstack((arr1,arr2))             #hstack for horizontal merging

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [89]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [90]:
#by using axis
np.concatenate((arr1,arr2),axis = 0)                
np.concatenate((arr1,arr2))                 #both will give same results as both default axis is 0

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [91]:
np.concatenate((arr2,arr1),axis = 1)

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

In [94]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
#split the array 
np.hsplit(arr1,2)             #split the array horizontally in pair of 2 (if we are splittig the array in pair of 2 horizontally then the number of elements in row should be even)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [104]:
#to split vertically
arr1 = np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[2,3,4,5]])

np.vsplit(arr1,2)             #split into arrays containing 2 pairs each vertically

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[2, 3, 4, 5],
        [2, 3, 4, 5]])]

In [105]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

Arrays Slicing - DAP

In [108]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
#calling the elements using index
arr[2]

3

In [111]:
#for more then one element
print(arr[2:])
print(arr[:-2])

[3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]


In [121]:
#for 2 dimensions
arr1 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [2,3,4,5],
                 [2,3,4,5]])
arr1[ 1:, : ]                             #[for rows : for columns]
arr1[ 1:2, 3: ] 
arr1[2,:]                                  #to access one particular row or column
arr1[1: ,1:2]
arr1[2,3]                                  #print the element at 2,3
arr1[1:,1:]                                #cropping the first row and column

array([[6, 7, 8],
       [3, 4, 5],
       [3, 4, 5]])

Automating using Numpy

In [124]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
arr>5                        #give true for values greater than 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [128]:
#to print the elements greater than 5
arr[arr>5]

array([6, 7, 8, 9])

In [129]:
#to print length
len(arr[arr>4])

5

In [131]:
#other airthmatic operations (without using loop)
print(arr[arr % 2 == 0 ])
print(len(arr[arr%2==0]))


[2 4 6 8]
4
