In [2]:
import numpy as np

Conversion of list into numpy array

In [3]:
lst = [1,2,3,4,5]
arr = np.array(lst)
print(arr)
print(len(arr))
print(type(arr))
arr = np.array(lst, ndmin=2)               #converting list into multidimensional array
print(arr)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
[[1 2 3 4 5]]


#Arrange fuction

In [4]:
arr = np.arange(10)           #generate random number from 0
print(arr)
arr = np.arange(1,10)         #(starting value, ending-1)
print(arr)
arr = np.arange(1,10,2)       #(starting value, ending-1,gap)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


#Multidimensional Array

In [5]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#Size function

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print("Total Size: ",arr.size)
print("Rows:",np.size(arr,0))                 # 0 axis for rows
print("Columns:",np.size(arr,1))              # 1 axis for columns

Total Size:  12
Rows: 4
Columns: 3


#Shape Function

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
print((np.size(arr,0),np.size(arr,1)))
print("Shape of array:",arr.shape)

(4, 3)
Shape of array: (4, 3)


#Dtype Function

In [8]:
arr1 = np.array([1,2,3,1,2,3])
arr2 = np.array([[1,2,3],[1,2,3]])
print(arr1.ndim)
print(arr2.ndim)

arr3 = np.array(arr1,ndmin=3)
print(arr3.ndim)
arr3



1
2
3


array([[[1, 2, 3, 1, 2, 3]]])

#Zeros Function

In [9]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


Ones Function

In [10]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


#Eye Function

In [11]:
arr = np.eye(3,3)
print(arr)
arr1 = np.eye(2)
print(arr1)
arr1 = np.eye(2,dtype=int)                #to get a integer value
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1 0]
 [0 1]]


#Empty Function

In [12]:
#same as np.zeros
np.empty(shape = (2,3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [4.9e-324, 9.9e-324, 1.5e-323]])

#Random Functions

In [13]:
#generate random values from 0 to 1
print(np.random.rand(2,3))
print()
print(np.random.rand(23))

[[0.74450096 0.11129451 0.29831522]
 [0.73285168 0.10177054 0.13181398]]

[0.74703153 0.32747085 0.54045721 0.45348814 0.46158384 0.83945446
 0.43395363 0.85586206 0.14389979 0.69764184 0.719443   0.87136561
 0.40811825 0.29997704 0.67904616 0.55321635 0.2445165  0.15047486
 0.63387448 0.7742348  0.14441005 0.66877401 0.28649179]


In [14]:
#to generate integer
print(np.random.randint(low = 1,high = 40, size = 23))
print(np.random.randint(2,34,3))                               #(starting,ending, size)
print(np.random.randint(2,34))                                 #if we don't define size then it will generate one integer

[33  9 12 30 31  4 35 30 28 29 38 17  4  8  7  1 25 23 39 15 26 32 30]
[9 5 7]
15


In [15]:
np.random.randn(100)

array([-1.59944585, -1.68538479, -0.27683053, -0.13577636, -0.68046154,
        0.61779059,  0.11275907,  0.78288647, -0.36944339,  1.00393158,
       -1.48813362, -1.27196738,  0.44744596, -1.35510402, -0.79647535,
        1.44181882,  1.50577688, -1.14388182,  0.67964648, -0.38932254,
       -0.81701217, -0.36816984,  0.49172258,  1.57384155,  0.107023  ,
       -0.02115963, -0.27009677,  0.07737239,  0.98536055, -0.18472386,
       -0.80810717,  0.81180036, -0.83388199, -1.38556775,  0.9708131 ,
        1.08780014,  0.50779687,  0.17961257,  0.54492551,  0.69440245,
       -0.55823832,  0.38965536, -1.08944883,  1.19024335, -2.57091795,
       -0.36348121,  1.75280396, -0.99001978,  0.39170675, -1.16243362,
       -0.28232167, -0.5651332 , -0.79927189, -1.13445744,  0.6650313 ,
       -1.41756089, -1.81303957, -0.72454923,  0.60716848, -1.50301247,
        0.79554007,  0.4755812 , -0.79174347,  1.02993483, -1.98328909,
       -1.72044464, -0.94481512,  1.41997385,  0.81973506, -1.76

#Reshape Function

In [16]:
arr = np.random.randint(1,100,size = (2,3))          #(start,end,size)
print(arr)
print(arr.reshape(3,2))             #reshape the array from (2,3) to (3,2)

#if we reshape array form (a,b) to (c,d) then there should be ab = cd


[[51 59 67]
 [73 90 49]]
[[51 59]
 [67 73]
 [90 49]]


#Linspace Function

In [17]:
np.linspace(1,10,4)                                 #all these values are equidistant from each other

array([ 1.,  4.,  7., 10.])

#Flatten Array

In [18]:
arr = np.random.randint(2,29,size=(2,5))
print(arr.shape,"\n")
print(arr,"\n")
arr= arr.flatten()                          #flatten a array
print(arr,"\n")

(2, 5) 

[[ 4  3 23 23 14]
 [16 20  6 21 10]] 

[ 4  3 23 23 14 16 20  6 21 10] 



#Logspace Function

In [19]:
print(np.logspace(2,19,12))                          #equal distace based on log
print("-"*50)
print(np.logspace(2,19,12,base=2))

[1.00000000e+02 3.51119173e+03 1.23284674e+05 4.32876128e+06
 1.51991108e+08 5.33669923e+09 1.87381742e+11 6.57933225e+12
 2.31012970e+14 8.11130831e+15 2.84803587e+17 1.00000000e+19]
--------------------------------------------------
[4.00000000e+00 1.16758408e+01 3.40813149e+01 9.94820020e+01
 2.90384006e+02 8.47619359e+02 2.47416718e+03 7.22199556e+03
 2.10807177e+04 6.15337762e+04 1.79614644e+05 5.24288000e+05]


#Copy Function

In [20]:
arr = np.random.randint(2,20,12)
arr1 = arr
print(arr, id(arr))
print(arr1,id(arr1))
#both id are same
print("-"*50)
arr2 = np.random.randint(2,20,12)
arr3 = np.copy(arr2)
print(arr2,id(arr2))
print(arr3,id(arr3))
#both id are different

[ 5 15  9  6 10  5  9  3 17 10 18 19] 136815861459984
[ 5 15  9  6 10  5  9  3 17 10 18 19] 136815861459984
--------------------------------------------------
[ 2 19 17  4  3  4 10  7 17 11  3  5] 136815861459888
[ 2 19 17  4  3  4 10  7 17 11  3  5] 136815861453072


#arr.max(),    arr.min(),     arr.sum() functions

In [21]:
arr = np.random.randint(0,30,15)
print(arr)
print(arr.max())
print(arr.min())
print(arr.sum())


[ 2  5  7  4 10 24 27 22 11 10  3 19  7 18  8]
27
2
177


####For particular rows and columns

We can use the axis parameter to get the max, min and sum of a particular column or row


*   axis=0 for the column
*   axis=1 for the row

In [22]:
arr = np.random.randint(2,10,size= (3,5))
print(arr)
print("-"*50)
#For rows
print("Row wise: ")
print("MAX: ",arr.max(axis=1))
print("MIN: ",arr.min(axis=1))
print("SUM: ",arr.sum(axis=1))
print("-"*50)
#For columns
print("Column wise: ")
print("MAX: ",arr.max(axis=0))
print("MIN: ",arr.min(axis=0))
print("SUM: ",arr.sum(axis=0))


[[9 8 5 5 2]
 [2 2 5 6 8]
 [4 3 6 2 2]]
--------------------------------------------------
Row wise: 
MAX:  [9 8 6]
MIN:  [2 2 2]
SUM:  [29 23 17]
--------------------------------------------------
Column wise: 
MAX:  [9 8 6 6 8]
MIN:  [2 2 5 2 2]
SUM:  [15 13 16 13 12]


#Seed Funtion

In [23]:
np.random.seed(11)
arr = np.random.randint(1,10,(2,3))
print(arr)
arr1 = np.random.randint(1,10,(2,3))
print(arr1)

#for a seed value 11 the values inside arr,arr1 won't change


[[1 2 8]
 [2 8 3]]
[[9 1 1]
 [5 3 2]]


now here the seed value is defined for **np.random** so whenever we define **arr** and **arr1** we need to define in such a way that suits the seed function and it will generate that same value until and unless we change that seed value

In [24]:
arr = np.random.randint(1,6)
print(arr)


3


#Sorting Funtion

In [25]:
np.random.seed(10)
arr = np.random.randint(1,10,(3,5))
print(arr)
print("-"*50)
print(np.sort(arr))
#we can sort row and column wise as well
print("-"*50)
print("Column wise: ")
print(np.sort(arr,axis = 0))
print("-"*50)
print("Row wise: ")
print(np.sort(arr,axis = 1))

[[5 1 2 1 2]
 [9 1 9 7 5]
 [4 1 5 7 9]]
--------------------------------------------------
[[1 1 2 2 5]
 [1 5 7 9 9]
 [1 4 5 7 9]]
--------------------------------------------------
Column wise: 
[[4 1 2 1 2]
 [5 1 5 7 5]
 [9 1 9 7 9]]
--------------------------------------------------
Row wise: 
[[1 1 2 2 5]
 [1 5 7 9 9]
 [1 4 5 7 9]]


In [26]:
#We can also do sorting like
arr = arr.flatten()
print(np.sort(arr))
print(np.sort(arr.flatten()))
arr = np.sort(arr.flatten())
#now can reshape this in original form
arr = arr.reshape(3,5)
print(arr)

# arr = np.reshape(np.sort(arr.flatten()),arr.shape)

[1 1 1 1 2 2 4 5 5 5 7 7 9 9 9]
[1 1 1 1 2 2 4 5 5 5 7 7 9 9 9]
[[1 1 1 1 2]
 [2 4 5 5 5]
 [7 7 9 9 9]]


#Mathematical Operation

## -Addition



In [27]:
print(arr)
# to add any number to every element of the array
print("-"*50)
print(arr+10)
print("-"*50)
print(np.add(arr,10))
print("-"*50)
print(np.add(arr,arr))          #add array to array
print("-"*50)
print(np.add(arr,arr,dtype=float))

[[1 1 1 1 2]
 [2 4 5 5 5]
 [7 7 9 9 9]]
--------------------------------------------------
[[11 11 11 11 12]
 [12 14 15 15 15]
 [17 17 19 19 19]]
--------------------------------------------------
[[11 11 11 11 12]
 [12 14 15 15 15]
 [17 17 19 19 19]]
--------------------------------------------------
[[ 2  2  2  2  4]
 [ 4  8 10 10 10]
 [14 14 18 18 18]]
--------------------------------------------------
[[ 2.  2.  2.  2.  4.]
 [ 4.  8. 10. 10. 10.]
 [14. 14. 18. 18. 18.]]


# - Substraction

In [28]:
print(arr)
print("-"*50)
print(arr-10)
print("-"*50)
print(np.subtract(arr,10))

[[1 1 1 1 2]
 [2 4 5 5 5]
 [7 7 9 9 9]]
--------------------------------------------------
[[-9 -9 -9 -9 -8]
 [-8 -6 -5 -5 -5]
 [-3 -3 -1 -1 -1]]
--------------------------------------------------
[[-9 -9 -9 -9 -8]
 [-8 -6 -5 -5 -5]
 [-3 -3 -1 -1 -1]]


# - Multiplication

In [29]:
print(arr)
print("-"*50)
print(arr*10)
print("-"*50)
print(np.multiply(arr,10))

[[1 1 1 1 2]
 [2 4 5 5 5]
 [7 7 9 9 9]]
--------------------------------------------------
[[10 10 10 10 20]
 [20 40 50 50 50]
 [70 70 90 90 90]]
--------------------------------------------------
[[10 10 10 10 20]
 [20 40 50 50 50]
 [70 70 90 90 90]]


# - Divison

In [30]:
print(arr)
print("-"*50)
print(arr/10)
print("-"*50)
print(np.divide(arr,10))

[[1 1 1 1 2]
 [2 4 5 5 5]
 [7 7 9 9 9]]
--------------------------------------------------
[[0.1 0.1 0.1 0.1 0.2]
 [0.2 0.4 0.5 0.5 0.5]
 [0.7 0.7 0.9 0.9 0.9]]
--------------------------------------------------
[[0.1 0.1 0.1 0.1 0.2]
 [0.2 0.4 0.5 0.5 0.5]
 [0.7 0.7 0.9 0.9 0.9]]


# - Matrix Multiplication

In [31]:
arr1 = np.random.randint(1,10,(2,3))
arr2 = np.random.randint(1,10,(3,2))
print(arr1)
print("-"*50)
print(arr2)
print("-"*50)
print(arr1@arr2)
print("-"*50)
print(arr1.dot(arr2))
print("-"*50)
print("-"*50)
print(np.matmul(arr1,arr2))

[[2 9 5]
 [2 4 7]]
--------------------------------------------------
[[6 4]
 [7 2]
 [5 3]]
--------------------------------------------------
[[100  41]
 [ 75  37]]
--------------------------------------------------
[[100  41]
 [ 75  37]]
--------------------------------------------------
--------------------------------------------------
[[100  41]
 [ 75  37]]


# - Power

In [32]:
print(arr)
print(arr ** 3)
print("-"*50)
print(np.power(arr,3))

[[1 1 1 1 2]
 [2 4 5 5 5]
 [7 7 9 9 9]]
[[  1   1   1   1   8]
 [  8  64 125 125 125]
 [343 343 729 729 729]]
--------------------------------------------------
[[  1   1   1   1   8]
 [  8  64 125 125 125]
 [343 343 729 729 729]]


#Percentile Function

In [33]:
np.random.seed(2)
arr = np.random.randint(1,10,10)
print(arr)
arr = np.sort(arr)
print(arr)
print(np.percentile(arr,50))

[9 9 7 3 9 8 3 2 6 5]
[2 3 3 5 6 7 8 9 9 9]
6.5


#Mean, Variance and Standard deviation

In [35]:
arr = np.random.randint(1,10,10)
print(arr)
print("-"*50)
print(np.mean(arr))
print("-"*50)
print(np.average(arr))
print("-"*50)
print(np.median(arr))
print("-"*50)
print(np.var(arr))
print("-"*50)
print(np.std(arr))

[4 6 9 5 7 4 3 1 5 3]
--------------------------------------------------
4.7
--------------------------------------------------
4.7
--------------------------------------------------
4.5
--------------------------------------------------
4.61
--------------------------------------------------
2.147091055358389


#Filtering a numpy array

In [39]:
arr = np.arange(1,51)
print(arr)
print("-"*50)
print("arr>40: ",arr>40)
print("-"*50)
print("arr[arr>40]: ",arr[arr>40])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
--------------------------------------------------
arr>40:  [False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True  True  True  True  True  True  True
  True  True]
--------------------------------------------------
arr[arr>40]:  [41 42 43 44 45 46 47 48 49 50]


In [40]:
arr1 = arr[arr>34]
print(arr1)

[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#Transpose of array

In [41]:
arr = np.random.randint(1,10,(3,4))
print(arr)
print("-"*50)
print(arr.T)

[[5 2 8 9]
 [3 9 8 2]
 [7 9 6 4]]
--------------------------------------------------
[[5 3 7]
 [2 9 9]
 [8 8 6]
 [9 2 4]]


#Where Function

In [46]:
arr = np.random.randint(1,100,10)
print(arr)
print("-"*50)
print(np.where(arr>50))                    #gives the index
#to change the  array values that are greater than 50 into 100
# arr[arr>50] = 100
print(arr)
#or
print("-"*50)
print(np.where(arr%2==0,100,arr))
print(np.where(arr%2==0,'even',arr))

[94 81 41 71 75 38 60 18 16 31]
--------------------------------------------------
(array([0, 1, 3, 4, 6]),)
[94 81 41 71 75 38 60 18 16 31]
--------------------------------------------------
[100  81  41  71  75 100 100 100 100  31]
['even' '81' '41' '71' '75' 'even' 'even' 'even' 'even' '31']


#Merging array

In [47]:
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))
print(arr1)
print("-"*50)
print(arr2)
print("-"*50)
print(np.concatenate((arr1,arr2)))                      #default axis is 0
print("-"*50)
print(np.concatenate((arr1,arr2),axis=1))
print("-"*50)
print(np.vstack((arr1,arr2)))                            #vertical stack (axis = 0)
print("-"*50)
print(np.hstack((arr1,arr2)))                            #horizontal stack (axis = 1)

[[8 5 4 7]
 [2 5 1 9]]
--------------------------------------------------
[[6 5 3 8]
 [2 3 2 1]]
--------------------------------------------------
[[8 5 4 7]
 [2 5 1 9]
 [6 5 3 8]
 [2 3 2 1]]
--------------------------------------------------
[[8 5 4 7 6 5 3 8]
 [2 5 1 9 2 3 2 1]]
--------------------------------------------------
[[8 5 4 7]
 [2 5 1 9]
 [6 5 3 8]
 [2 3 2 1]]
--------------------------------------------------
[[8 5 4 7 6 5 3 8]
 [2 5 1 9 2 3 2 1]]


#Splitting Arrays

In [52]:
arr = np.random.randint(1,11,(2,4))
print(arr)
print("-"*50)
print(np.hsplit(arr,2))                              #to split the array horizontally or vertically we need to take care that if we split the array in segment of two the there should be even number of elements in the array and should in such a way that splitting could happen
print("-"*50)
print(np.vsplit(arr,2))

[[ 2  9  6 10]
 [ 6  5  3  8]]
--------------------------------------------------
[array([[2, 9],
       [6, 5]]), array([[ 6, 10],
       [ 3,  8]])]
--------------------------------------------------
[array([[ 2,  9,  6, 10]]), array([[6, 5, 3, 8]])]
